### PR TITLE
Adding Unemployed Occupation

### PR DESCRIPTION
**Pull request by edrisse**

### CODE REVIEW

**Comment by edrisse** [comment]
https://trello.com/c/UN2ZzNvw/39-431-add-fields-to-collect-the-patients-current-occupation-in-social-form-the-occupation-list-will-be-the-standard-list-provided

**Comment by ningosi** [comment]
Why is it picking commits from 21 days ago? @edrisse

**Comment by edrisse** [comment]
@ningosi possibly because the commits were squashed on my last PR. But if you see the changes, only the things that are supposed to be committed are being included in the PR.

**Comment by edrisse** [comment]
@ningosi I will submit a new PR

**Pull request closed without merging**
